### ISSUE TITLE
Error when trying mirroring a repo

### ISSUE THREAD

**Issue by svante66** [ef-labs/stash-hook-mirror#28]
Hey,

I am setting up this mirror for some of my Stash repos and it works well most of the times. However, for some repos I get the following error message in the log:

2014-09-04 13:49:27,903 ERROR [threadpool:thread-4178050] svante.gustafsson 825x62977372x0 1qr1w8r 1_._._._,127.0.0.1 "POST /rest/branch-utils/latest/projects/ESUP/repos/gitolite-admin/branches HTTP/1.0" c.e.stash.hook.MirrorRepositoryHook Failed to mirror repository gitolite-admin after 5 attempts.
com.atlassian.stash.exception.ServerException: An error occurred while executing an external process: '/usr/bin/git push --prune gitosis@git.internal.machines:gitolite-admin.git --force +refs/heads/_:refs/heads/_ +refs/tags/_:refs/tags/_' exited with code 129 saying: error: --mirror can't be combined with refspecs
usage: git push [<options>] [<repository> [<refspec>...]]

```
-v, --verbose         be more verbose
-q, --quiet           be more quiet
--repo <repository>   repository
--all                 push all refs
--mirror              mirror all refs
--delete              delete refs
--tags                push tags (can't be used with --all or --mirror)
-n, --dry-run         dry run
--porcelain           machine-readable output
-f, --force           force updates
--recurse-submodules[=<check>]
                      control recursive pushing of submodules
--thin                use thin pack
--receive-pack <receive-pack>
                      receive pack program
--exec <receive-pack>
                      receive pack program
-u, --set-upstream    set upstream for git pull/status
--progress            force progress reporting
--prune               prune locally removed refs
--no-verify           bypass pre-push hook
--follow-tags         push missing but relevant tags

at com.atlassian.stash.scm.git.common.command.GitCommandExitHandler.evaluateThrowable(GitCommandExitHandler.java:120) ~[na:na]
at com.atlassian.stash.scm.git.common.command.GitCommandExitHandler.onError(GitCommandExitHandler.java:163) ~[na:na]
at com.atlassian.stash.scm.DefaultCommandExitHandler.onExit(DefaultCommandExitHandler.java:34) ~[stash-spi-2.11.2.jar:na]
at com.englishtown.stash.hook.PasswordHandler.onExit(PasswordHandler.java:46) ~[plugin.2602867967957298015.stash-hook-mirror-1.9.0_1409046838000.jar:na]
at com.atlassian.stash.scm.BaseCommand.callExitHandler(BaseCommand.java:143) ~[stash-spi-2.11.2.jar:na]
at com.atlassian.stash.scm.BaseCommand$CommandFuture.internalGet(BaseCommand.java:256) ~[stash-spi-2.11.2.jar:na]
at com.atlassian.stash.scm.BaseCommand$CommandFuture.get(BaseCommand.java:225) ~[stash-spi-2.11.2.jar:na]
at com.atlassian.stash.scm.BaseCommand.call(BaseCommand.java:78) ~[stash-spi-2.11.2.jar:na]
at com.englishtown.stash.hook.MirrorRepositoryHook$1.call(MirrorRepositoryHook.java:127) [plugin.2602867967957298015.stash-hook-mirror-1.9.0_1409046838000.jar:na]
at com.englishtown.stash.hook.MirrorRepositoryHook$1.call(MirrorRepositoryHook.java:115) [plugin.2602867967957298015.stash-hook-mirror-1.9.0_1409046838000.jar:na]
at com.atlassian.stash.internal.concurrent.StateTransferringExecutorService$StateTransferringCallable.call(StateTransferringExecutorService.java:131) [stash-platform-2.11.2.jar:na]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_45]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_45]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_45]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
... 1 frame trimmed
```

Caused by: com.atlassian.utils.process.ProcessException: Non-zero exit code: 129
    at com.atlassian.stash.scm.SummarizingProcessHandler.complete(SummarizingProcessHandler.java:49) ~[stash-spi-2.11.2.jar:na]
    at com.atlassian.utils.process.ExternalProcessImpl.wrapUpProcess(ExternalProcessImpl.java:659) ~[atlassian-processutils-1.6.0-m1.jar:na]
    at com.atlassian.utils.process.ExternalProcessImpl.finish(ExternalProcessImpl.java:161) ~[atlassian-processutils-1.6.0-m1.jar:na]
    at com.atlassian.stash.scm.BaseCommand$CommandFuture.get(BaseCommand.java:223) ~[stash-spi-2.11.2.jar:na]
    ... 10 common frames omitted

I have no clue why this happens for some repos and not for other. I have checked our gitolite settings on the target server and the repos I am mirroring to have the same permission settings setup.

Can you help out here?

Thnx in advance!

// Svante

**Comment by tddmonkey** [comment]
Did you ever find a solution for this?

**Comment by adrianluisgonzalez** [comment]
We no longer use the `--mirror` flag:
https://github.com/ef-labs/stash-hook-mirror/blob/develop/src/main/java/com/englishtown/bitbucket/hook/MirrorRepositoryHook.java#L142
