### ISSUE TITLE
process timed out

### ISSUE THREAD

**Issue by PedroFonseca** [ef-labs/stash-hook-mirror#39]
Hi,

If i use https it works fine.
When i use ssh it doesn't work and i get a process timed out in the logs.
This is the error that i'm getting in the log:

2017-01-05 11:01:28,994 DEBUG [threadpool:thread-703] pmfonseca @MQ10L8x652x915x3 13sq5fn 192.168.1.136 SSH - git-receive-pack '/test/svc-fon.git' com.atlassian.stash.scm.BaseCommand Executed C:\Git\bin\git.exe push --prune ssh://git@pre-bitbucket.xxx.pt:7999/visioncenter/test.git --force +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
2017-01-05 11:01:29,001 ERROR [threadpool:thread-703] pmfonseca @MQ10L8x652x915x3 13sq5fn 192.168.1.136 SSH - git-receive-pack '/test/svc-fon.git' c.e.stash.hook.MirrorRepositoryHook Failed to mirror repository SVC-FON after 5 attempts.
com.atlassian.stash.exception.ServerException: An error occurred while executing an external process: process timed out
	at com.atlassian.stash.scm.git.common.command.GitCommandExitHandler.evaluateThrowable(GitCommandExitHandler.java:113) ~[na:na]
	at com.atlassian.stash.scm.git.common.command.GitCommandExitHandler.onError(GitCommandExitHandler.java:159) ~[na:na]
	at com.atlassian.stash.scm.DefaultCommandExitHandler.onExit(DefaultCommandExitHandler.java:33) ~[stash-spi-3.7.1.jar:na]
	at com.englishtown.stash.hook.PasswordHandler.onExit(PasswordHandler.java:46) ~[plugin.640321809486732222.stash-hook-mirror-1.9.0_1483467141180.jar:na]
	at com.atlassian.stash.scm.BaseCommand.callExitHandler(BaseCommand.java:138) ~[stash-spi-3.7.1.jar:na]
	at com.atlassian.stash.scm.BaseCommand$CommandFuture.internalGet(BaseCommand.java:251) ~[stash-spi-3.7.1.jar:na]
	at com.atlassian.stash.scm.BaseCommand$CommandFuture.get(BaseCommand.java:220) ~[stash-spi-3.7.1.jar:na]
	at com.atlassian.stash.scm.BaseCommand.call(BaseCommand.java:75) ~[stash-spi-3.7.1.jar:na]
	at com.englishtown.stash.hook.MirrorRepositoryHook$1.call(MirrorRepositoryHook.java:127) [plugin.640321809486732222.stash-hook-mirror-1.9.0_1483467141180.jar:na]
	at com.englishtown.stash.hook.MirrorRepositoryHook$1.call(MirrorRepositoryHook.java:115) [plugin.640321809486732222.stash-hook-mirror-1.9.0_1483467141180.jar:na]
	at com.atlassian.stash.internal.concurrent.StateTransferringExecutorService$StateTransferringCallable.call(StateTransferringExecutorService.java:147) [stash-platform-3.7.1.jar:na]
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [na:1.7.0_17]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_17]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.7.0_17]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_17]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_17]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_17]
	... 1 frame trimmed
Caused by: com.atlassian.utils.process.ProcessTimeoutException: process timed out
	at com.atlassian.utils.process.ExternalProcessImpl.wrapUpProcess(ExternalProcessImpl.java:656) ~[atlassian-processutils-1.6.0-m2.jar:na]
	at com.atlassian.utils.process.ExternalProcessImpl.finish(ExternalProcessImpl.java:161) ~[atlassian-processutils-1.6.0-m2.jar:na]
	at com.atlassian.stash.scm.BaseCommand$CommandFuture.get(BaseCommand.java:218) ~[stash-spi-3.7.1.jar:na]
	... 11 common frames omitted

Any thoughts?
Thanks in advance

**Comment by adrianluisgonzalez** [comment]
Does it work if you manually run the git mirror command?

`C:\Git\bin\git.exe push --prune ssh://git@pre-bitbucket.xxx.pt:7999/visioncenter/test.git --force +refs/heads/:refs/heads/ +refs/tags/:refs/tags/`

Is the ssh key added for the user bitbucket runs as?

**Comment by PedroFonseca** [comment]
i forgot to mention that i've already tryed the steps on #18.
Running manually it was showing the certificate error. Then i fixed it and it now runs manually.
Then i tried using the mirror hook and that's when it started to show this process timed out error in the logs.

**Comment by rushsimonson** [comment]
Experiencing the same issue. Appears to be tied to the size of the repository. I was able to mirror using HTTPS from the same Bitbucket server to CodeCommit, but our largest repo which is around 15GB is not Mirroring.
