### ISSUE TITLE
Mirror to Atlassian cloud?

### ISSUE THREAD

**Issue by alexdovn** [ef-labs/stash-hook-mirror#75]
Hello,

We have a problem with the Stash server plugin and mirroring. We install the plugin and first mirror to another Stash server. Works fine.

But when mirroring in the Atlassian cloud, we get an error like in a code block.

Maybe somebody solved the cloud mirroring issue?

`2019-10-18 11:28:57,122 INFO  [MirrorRepositoryHook:thread-3]  c.a.s.i.c.HazelcastBucketedExecutor Attempt 1 of 5 at processing bucket 'MirrorRepositoryHook@452:https://bitbucket.org/testcloudstash/testrepo.git' for executor 'MirrorRepositoryHook' failed: 'service proxy has been destroyed'

2019-10-18 11:28:57,122 DEBUG [MirrorRepositoryHook:thread-3]  c.a.s.i.c.HazelcastBucketedExecutor Exception:

org.eclipse.gemini.blueprint.service.importer.ServiceProxyDestroyedException: service proxy has been destroyed

    at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceDynamicInterceptor$ServiceLookUpCallback.doWithRetry(ServiceDynamicInterceptor.java:101)

    at org.eclipse.gemini.blueprint.service.importer.support.internal.support.RetryTemplate.execute(RetryTemplate.java:81)

    at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceDynamicInterceptor.lookupService(ServiceDynamicInterceptor.java:427)

    at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceDynamicInterceptor.getTarget(ServiceDynamicInterceptor.java:400)

    at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)

    at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)

    at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)

    at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)

    at com.englishtown.bitbucket.hook.MirrorBucketProcessor.lambda$process$0(MirrorBucketProcessor.java:68)

    at com.atlassian.stash.internal.user.DefaultEscalatedSecurityContext.call(DefaultEscalatedSecurityContext.java:58)

    at com.englishtown.bitbucket.hook.MirrorBucketProcessor.process(MirrorBucketProcessor.java:67)

    at com.atlassian.stash.internal.concurrent.HazelcastBucketedExecutor$BucketProcessingBootstrapper.run(HazelcastBucketedExecutor.java:146)

    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

    at java.util.concurrent.FutureTask.run(FutureTask.java:266)

    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

    at java.lang.Thread.run(Thread.java:748)

    ... 12 frames trimmed`

**Comment by adrianluisgonzalez** [comment]
Quick google search suggests it might be an OSGi issue related to de-activating and re-activating the plugin.  Are able to restart bitbucket at some point and see if the problem persists?
