### ISSUE TITLE
Error running MirrorRepositoryHook validate

### ISSUE THREAD

**Issue by mikosh75** [ef-labs/stash-hook-mirror#84]
Hello,
after upgrading to v3.1, the hook is not working anymore, with this error

```
2020-08-31 18:47:55,711 ERROR [http-nio-7990-exec-57] <user> @JNKL7Qx1127x1602902x0 1y7degk 2.229.36.64,0:0:0:0:0:0:0:1 "PUT /rest/api/latest/projects/EPHO/repos/xcrf/settings/hooks/com.englishtown.stash-hook-mirror:mirror-repository-hook/enabled HTTP/1.1" c.e.b.hook.MirrorRepositoryHook Error running MirrorRepositoryHook validate.
java.lang.ClassCastException: com.englishtown.bitbucket.hook.MirrorRequest cannot be cast to com.englishtown.bitbucket.hook.MirrorRequest
        at com.englishtown.bitbucket.hook.MirrorRepositoryHook.lambda$schedulePushes$0(MirrorRepositoryHook.java:177)
        at com.englishtown.bitbucket.hook.MirrorRepositoryHook.schedulePushes(MirrorRepositoryHook.java:177)
        at com.englishtown.bitbucket.hook.MirrorRepositoryHook.validate(MirrorRepositoryHook.java:138)

```

Also when i try to save again the setting, i get the same error

![image](https://user-images.githubusercontent.com/871966/91745760-c6815d80-ebbb-11ea-95ef-ab5302771bf3.png)

Also tried to remove and reinstall, but same issue.
Please help!
Thanks
Michele

**Comment by adrianluisgonzalez** [comment]
This looks like the same issue as #83 .  It appears Bitbucket is keeping the types from the old plugin jar in memory somewhere causing the `ClassCastException`.   Can you try restarting Bitbucket Server?

**Comment by daurrutia** [comment]
Same issue here. Server restart was the workaround.

**Comment by Jahimees** [comment]
And again for people who have the same issue. I know it's been a long time. But if necessary, I adapted the plugin for version 8.* and added the ability to authenticate with a personal token.
https://github.com/Jahimees/stash-hook-mirror
